# Jekyll Library Website Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: University of Idaho Library 
tagline: "Bringing the world to Idaho ... and Idaho to the world." 
description: "As Idaho's flagship research library, the University of Idaho Library connects our users with information, ideas, tools, and spaces; enriches formal and informal learning opportunities; supports and advances research, scholarly, and creative activity; builds partnerships through regional and national outreach; and preserves university, state, and regional historical archives." 
keywords: Idaho, research library, University of Idaho, Humanities, Science, Social Sciences, Engineering
email: ewilliamson@uidaho.edu

# url variables
url: https://www.lib.uidaho.edu
baseurl: 
# dev urls for testweb
# url: https://testweb.lib.uidaho.edu
# baseurl: 
# dev urls for gh-pages
#url: https://uidaholib.github.io
#baseurl: /main-web-redesign_draft

liburl: https://www.lib.uidaho.edu

exclude: [old, lib-apps]