####
#
# Default open hours
# must include display messages for mon,tue,wed,thu,fri,sat,sun 
#
####
default: 
  # fall 2021
  mon: "Open 6am &#8211; 2am"
  tue: "Open 6am &#8211; 2am"
  wed: "Open 6am &#8211; 2am"
  thu: "Open 6am &#8211; 2am"
  fri: "Open 6am &#8211; 8pm"
  sat: "Open 12pm &#8211; 6pm"
  sun: "Open 12pm &#8211; 2am"
####
#
# Breaks open hours (longer term hours that apply to extended periods)
# each break is one list item,
# must include values for start and end (iso date format),
# and display messages mon,tue,wed,thu,fri,sat,sun
#
####
breaks:   
  # thanksgiving 
  - start: "2021-11-21"
    end: "2021-11-27"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Closed"
    fri: "Open 12pm &#8211; 6pm"
    sat: "Open 12pm &#8211; 6pm"
    sun: "Open 12pm &#8211; 6pm"
  # winter 1
  - start: "2021-12-19"
    end: "2021-12-23"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Open 8am &#8211; 6pm"
    fri: "Closed"
    sat: "Closed"
    sun: "Open 12pm &#8211; 6pm"
  # winter 2
  - start: "2022-01-02"
    end: "2022-01-09"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Open 8am &#8211; 6pm"
    fri: "Open 8am &#8211; 6pm"
    sat: "Open 12pm &#8211; 6pm"
    sun: "Open 12pm &#8211; 6pm"       
  # spring break
  - start: "2022-03-14"
    end: "2022-03-19"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Open 8am &#8211; 6pm"
    fri: "Open 8am &#8211; 6pm"
    sat: "Open 12pm &#8211; 6pm"
    sun: "Open 12pm &#8211; 8pm" 
 # summer break
  - start: "2021-05-16"
    end: "2021-08-22"
    mon: "Open 8am &#8211; 8pm"
    tue: "Open 8am &#8211; 8pm"
    wed: "Open 8am &#8211; 8pm"
    thu: "Open 8am &#8211; 8pm"
    fri: "Open 8am &#8211; 8pm"
    sat: "Closed"
    sun: "Open 12pm &#8211; 8pm"     
####
#
# Special dates (hours that apply to single dates)
# each specials is a list item, 
# must include a list of dates (iso date format),
# plus a display message
# 
####
specials:
  - dates: ["2021-07-05"]
    message: "Open 12pm &#8211; 5pm"  
####
#
# Closed dates (single dates when closed)
# must provide a list of dates (iso date format),
# plus a display message
# 
####
closed:
  dates: [ "2021-09-06","2021-12-24","2021-12-25","2021-12-26","2021-12-27","2021-12-28","2021-12-29","2021-12-30","2021-12-31","2022-01-01"]
  message: "Closed"
