####
#
# Default open hours
# must include open and close keys for mon,tue,wed,thu,fri,sat,sun 
# the open key should = false if closed
#
####
default: 
  # fall 2022
  mon: 
    open: 6am
    close: 2am
  tue: 
    open: 6am
    close: 2am  
  wed: 
    open: 6am
    close: 2am  
  thu: 
    open: 6am
    close: 2am  
  fri: 
    open: 6am
    close: 8pm
  sat: 
    open: 12pm
    close: 6pm  
  sun: 
    open: 12pm
    close: 2am  
####
#
# Breaks open hours (longer term hours that apply to extended periods)
# each break is one list item,
# must include values for start and end (iso date format),
# and open and close keys for mon,tue,wed,thu,fri,sat,sun
# the open key should = false if closed
#
####
breaks:   
  # thanksgiving 
  - start: "2022-11-19"
    end: "2022-11-26"
    mon: 
      open: 8am
      close: 6pm
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 6pm    
    thu: 
      open: false
      close: false
      # message: "Closed - Happy Thanksgiving!"
    fri: 
      open: 12pm
      close: 6pm    
    sat: 
      open: 12pm
      close: 6pm    
    sun: 
      open: 12pm
      close: 6pm    
  # winter 1
  - start: "2022-12-17"
    end: "2022-12-23"
    mon:
      open: 8am
      close: 6pm
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 6pm    
    thu: 
      open: 8am
      close: 6pm    
    fri: 
      open: false
      close: false
    sat: 
      open: 12pm
      close: 6pm    
    sun:
      open: 12pm
      close: 6pm    
  # winter 2
  - start: "2023-01-02"
    end: "2023-01-08"
    mon: 
      open: false
      close: false    
    tue: 
      open: 8am
      close: 6pm     
    wed: 
      open: 8am
      close: 6pm     
    thu: 
      open: 8am
      close: 6pm     
    fri: 
      open: 8am
      close: 6pm     
    sat: 
      open: 12pm
      close: 6pm     
    sun: 
      open: 12pm
      close: 6pm           
  # spring break
  - start: "2023-03-11"
    end: "2023-03-18"
    mon:
      open: 8am
      close: 6pm      
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 6pm    
    thu: 
      open: 8am
      close: 6pm      
    fri: 
      open: 8am
      close: 6pm      
    sat: 
      open: 12pm
      close: 6pm      
    sun: 
      open: 12pm
      close: 6pm      
  # summer break
  - start: "2022-05-15"
    end: "2022-08-21"
    mon: 
      open: 8am
      close: 8pm 
    tue: 
      open: 8am
      close: 8pm    
    wed: 
      open: 8am
      close: 8pm    
    thu: 
      open: 8am
      close: 8pm    
    fri: 
      open: 8am
      close: 8pm    
    sat: 
      open: false
      close: false   
    sun:      
      open: 12pm
      close: 8pm    
####
#
# Special dates (hours that apply to single dates)
# each specials is a list item, 
# must include a list of dates (iso date format),
# open and close keys or a display message
# 
####
specials:
  - dates: ["2022-09-04","2023-01-15","2023-01-16","2023-02-19","2023-02-20"]
    open: 12pm
    close: 12am
    # message: "Open 12pm &#8211; 12am"   
####
#
# Closed dates (single dates when closed)
# must provide a list of dates (iso date format),
# plus a display message
# 
####
closed:
  dates: [ "2022-09-05","2022-12-24","2022-12-25","2022-12-26","2022-12-27","2022-12-28","2022-12-29","2022-12-30","2022-12-31","2023-01-01","2023-05-29","2023-06-19","2023-07-04"]
  message: "Closed"
