####
#
# Default open hours
# must include display messages for mon,tue,wed,thu,fri,sat,sun 
#
####
default: 
  # reopening phase 3 
  mon: "Open 7:45am &#8211; 10pm"
  tue: "Open 7:45am &#8211; 10pm"
  wed: "Open 7:45am &#8211; 10pm"
  thu: "Open 7:45am &#8211; 10pm"
  fri: "Open 7:45am &#8211; 8pm"
  sat: "Closed"
  sun: "Open 12pm &#8211; 10pm"
####
#
# Breaks open hours (longer term hours that apply to extended periods)
# each break is one list item,
# must include values for start and end (iso date format),
# and display messages mon,tue,wed,thu,fri,sat,sun
#
####
breaks:   
  # thanksgiving 
  - start: "2020-11-23"
    end: "2020-11-29"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Closed"
    fri: "Closed"
    sat: "Closed"
    sun: "Open 10am &#8211; 6pm"
  # winter 
  - start: "2020-12-21"
    end: "2021-01-14"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Open 8am &#8211; 6pm"
    fri: "Open 8am &#8211; 6pm"
    sat: "Open 10am &#8211; 6pm"
    sun: "Open 10am &#8211; 6pm"
  # spring
#  - start: "2021-03-13"
#    end: "2021-03-21"
#    mon: "Open 8am &#8211; 6pm"
#    tue: "Open 8am &#8211; 6pm"
#    wed: "Open 8am &#8211; 6pm"
#    thu: "Open 8am &#8211; 6pm"
#    fri: "Open 8am &#8211; 6pm"
#    sat: "Open 10am &#8211; 6pm"
#    sun: "Open 10am &#8211; 6pm" 
  # summer break
#  - start: "2021-06-14"
#    end: "2021-09-24"
#    mon: "Open 7am &#8211; 7pm"
#    tue: "Open 7am &#8211; 7pm"
#    wed: "Open 7am &#8211; 7pm"
#    thu: "Open 7am &#8211; 7pm"
#    fri: "Open 7am &#8211; 7pm"
#    sat: "Open 10am &#8211; 6pm"
#    sun: "Open 10am &#8211; 6pm"     
####
#
# Special dates (hours that apply to single dates)
# each specials is a list item, 
# must include a list of dates (iso date format),
# plus a display message
# 
####
specials:
  - dates: ["2020-05-16","2020-05-17"]
    message: "Open 8am &#8211; 5pm"
  - dates: ["2020-11-22"]
    message: "Open 12pm &#8211; 6pm"    
####
#
# Closed dates (single dates when closed)
# must provide a list of dates (iso date format),
# plus a display message
# 
####
closed:
  dates: [ "2020-09-14","2020-08-16","2020-08-23","2020-09-07","2020-11-26","2020-12-24","2020-12-25","2020-12-31","2021-01-01","2021-05-31","2021-07-05"]
  message: "Closed"
