####
#
# Default open hours
# must include open and close keys for mon,tue,wed,thu,fri,sat,sun 
# the open key should = false if closed
#
####
default: 
  # fall 2023
  mon: 
    open: 6am
    close: 2am
  tue: 
    open: 6am
    close: 2am  
  wed: 
    open: 6am
    close: 2am  
  thu: 
    open: 6am
    close: 2am  
  fri: 
    open: 6am
    close: 8pm
  sat: 
    open: 12pm
    close: 6pm  
  sun: 
    open: 12pm
    close: 2am  
####
#
# Breaks open hours (longer term hours that apply to extended periods)
# each break is one list item,
# must include values for start and end (iso date format),
# and open and close keys for mon,tue,wed,thu,fri,sat,sun
# the open key should = false if closed
#
####
breaks:   
  # thanksgiving 
  - start: "2023-11-19"
    end: "2023-11-25"
    mon: 
      open: 8am
      close: 6pm
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 4pm    
    thu: 
      open: false
      close: false
      # message: "Closed - Happy Thanksgiving!"
    fri: 
      open: 12pm
      close: 6pm    
    sat: 
      open: 12pm
      close: 6pm    
    sun: 
      open: 12pm
      close: 6pm    
  # winter 1
  - start: "2023-12-16"
    end: "2023-12-21"
    mon:
      open: 8am
      close: 6pm
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 6pm    
    thu: 
      open: 8am
      close: 6pm    
    fri: 
      open: 8am
      close: 6pm
    sat: 
      open: 12pm
      close: 6pm    
    sun:
      open: 12pm
      close: 6pm    
  # winter 2
  - start: "2024-01-02"
    end: "2024-01-07"
    mon: 
      open: 8am
      close: 6pm    
    tue: 
      open: 8am
      close: 6pm     
    wed: 
      open: 8am
      close: 6pm     
    thu: 
      open: 8am
      close: 6pm     
    fri: 
      open: 8am
      close: 6pm     
    sat: 
      open: 12pm
      close: 6pm     
    sun: 
      open: 12pm
      close: 6pm           
  # spring break
  - start: "2024-03-09"
    end: "2024-03-16"
    mon:
      open: 8am
      close: 6pm      
    tue: 
      open: 8am
      close: 6pm    
    wed: 
      open: 8am
      close: 6pm    
    thu: 
      open: 8am
      close: 6pm      
    fri: 
      open: 8am
      close: 6pm      
    sat: 
      open: 12pm
      close: 6pm      
    sun: 
      open: 12pm
      close: 6pm      
  # summer break
  - start: "2024-05-11"
    end: "2024-08-18"
    mon: 
      open: 8am
      close: 8pm 
    tue: 
      open: 8am
      close: 8pm    
    wed: 
      open: 8am
      close: 8pm    
    thu: 
      open: 8am
      close: 8pm    
    fri: 
      open: 8am
      close: 8pm    
    sat: 
      open: false
      close: false   
    sun:      
      open: 12pm
      close: 8pm    
####
#
# Special dates (hours that apply to single dates)
# each specials is a list item, 
# must include a list of dates (iso date format),
# open and close keys or a display message
# 
####
specials:
  - dates: ["2023-09-03","2024-01-15","2024-02-19"]
    open: 12pm
    close: 12am
  - dates: ["2022-12-06"]
    open: 6am
    close: 12am  
    # message: "Open 12pm &#8211; 12am"   
####
#
# Closed dates (single dates when closed)
# must provide a list of dates (iso date format),
# plus a display message
# 
####
closed:
  dates: [ "2023-09-04","2023-12-22","2023-12-23","2023-12-24","2023-12-25","2023-12-26","2023-12-27","2023-12-28","2023-12-29","2023-12-30","2023-12-31","2024-01-01","2024-05-27","2024-06-19","2024-06-28","2024-07-04"]
  message: "Closed"
