####
#
# Default open hours
# must include display messages for mon,tue,wed,thu,fri,sat,sun 
#
####
default: 
  # reopening phase 3 
  mon: "Open 7:45am &#8211; 1am"
  tue: "Open 7:45am &#8211; 1am"
  wed: "Open 7:45am &#8211; 1am"
  thu: "Open 7:45am &#8211; 1am"
  fri: "Open 7:45am &#8211; 8pm"
  sat: "Closed"
  sun: "Open 12pm &#8211; 1am"
####
#
# Breaks open hours (longer term hours that apply to extended periods)
# each break is one list item,
# must include values for start and end (iso date format),
# and display messages mon,tue,wed,thu,fri,sat,sun
#
####
breaks:   
  # thanksgiving 
#  - start: "2020-11-22"
#    end: "2020-11-29"
#    mon: "Open 8am &#8211; 6pm"
#    tue: "Open 8am &#8211; 6pm"
#    wed: "Open 8am &#8211; 6pm"
#    thu: "Closed"
#    fri: "Open 12pm &#8211; 6pm"
#    sat: "Closed"
#    sun: "Open 12pm &#8211; 6pm"
  # winter 1
#  - start: "2020-12-19"
#    end: "2020-12-23"
#    mon: "Open 8am &#8211; 6pm"
#    tue: "Open 8am &#8211; 6pm"
#    wed: "Open 8am &#8211; 6pm"
#    thu: "Open 8am &#8211; 6pm"
#    fri: "Open 8am &#8211; 6pm"
#    sat: "Closed"
#    sun: "Open 12pm &#8211; 6pm"   
  # spring break
  - start: "2021-03-14"
    end: "2021-03-20"
    mon: "Open 8am &#8211; 6pm"
    tue: "Open 8am &#8211; 6pm"
    wed: "Open 8am &#8211; 6pm"
    thu: "Open 8am &#8211; 6pm"
    fri: "Open 8am &#8211; 6pm"
    sat: "Closed"
    sun: "Open 12pm &#8211; 8pm" 
  # summer break
#  - start: "2021-06-14"
#    end: "2021-09-24"
#    mon: "Open 7am &#8211; 7pm"
#    tue: "Open 7am &#8211; 7pm"
#    wed: "Open 7am &#8211; 7pm"
#    thu: "Open 7am &#8211; 7pm"
#    fri: "Open 7am &#8211; 7pm"
#    sat: "Open 10am &#8211; 6pm"
#    sun: "Open 10am &#8211; 6pm"     
####
#
# Special dates (hours that apply to single dates)
# each specials is a list item, 
# must include a list of dates (iso date format),
# plus a display message
# 
####
specials:
  - dates: ["2021-01-11","2021-01-12"]
    message: "Open 7:45am &#8211; 10pm"  
####
#
# Closed dates (single dates when closed)
# must provide a list of dates (iso date format),
# plus a display message
# 
####
closed:
  dates: [ "2020-09-14","2020-08-16","2020-08-23","2020-09-07","2021-02-16","2021-05-31","2021-07-04"]
  message: "Closed"
